/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("application-conventions")
    id("org.springframework.boot")
    id("io.spring.dependency-management")
    id("io.freefair.lombok")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":hellojpa-domain"))

    implementation("org.springframework.boot:spring-boot-starter-web")
}

/* application 해당 부분은 없어도 됨 */
application {
    // Define the main class for the application.
    mainClass.set("io.moon.front.FrontApp")
}
