/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.moon.front;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class FrontApp {

    public static void main(String[] args) {
        SpringApplication.run(FrontApp.class, args);
    }

}
