/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.moon.app;

import io.moon.list.LinkedList;

import static io.moon.utilities.StringUtils.join;
import static io.moon.utilities.StringUtils.split;
import static io.moon.app.MessageUtils.getMessage;

import org.apache.commons.text.WordUtils;

public class App {
    public static void main(String[] args) {
        LinkedList tokens;
        tokens = split(getMessage());
        String result = join(tokens);
        System.out.println(WordUtils.capitalize(result));
    }
}
